name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Menggunakan runner yang berjalan di server Ubuntu
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install Dependencies & Migrate
        run: |
          npm install
          npm run migrate
          
      - name: Restart Application
        run: |
          # Jika Anda menjalankan aplikasi langsung dengan PM2 di host:
          pm2 restart forum-api
          