name: Continuous Deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    
    runs-on: self-hosted 
    
    steps:
      - name: Deploy Aplikasi
        run: |
          # Alamat folder server
          cd lab-server/03-projects/dicoding/dicoding-backend-developer-expert 
          
          # Menarik kode terbaru
          git pull origin main
          
          # Install dependencies
          npm install
          
          # Menjalankan migrasi database
          npm run migrate up
          
          # Restart aplikasi (Sesuaikan dengan cara Anda menjalankan Express, misal dengan PM2)
          pm2 restart forum-api